package com.cbt.entity;
// Generated 12-Jan-2020 16:42:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Participant generated by hbm2java
 */
@Entity
@Table(name="participant"
    ,catalog="computerbasedtest"
)
public class Participant  implements java.io.Serializable {


     private String id;
     private Institute institute;
     private String username;
     private String password;
     private String firstName;
     private String lastName;
     private String email;
     private Set<Score> scores = new HashSet<Score>(0);

    public Participant() {
    }

	
    public Participant(String id, Institute institute, String username, String password, String firstName) {
        this.id = id;
        this.institute = institute;
        this.username = username;
        this.password = password;
        this.firstName = firstName;
    }
    public Participant(String id, Institute institute, String username, String password, String firstName, String lastName, String email, Set<Score> scores) {
       this.id = id;
       this.institute = institute;
       this.username = username;
       this.password = password;
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.scores = scores;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=11)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Institute_id", nullable=false)
    public Institute getInstitute() {
        return this.institute;
    }
    
    public void setInstitute(Institute institute) {
        this.institute = institute;
    }

    
    @Column(name="username", nullable=false, length=24)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=24)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="first_name", nullable=false, length=50)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", length=50)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="email", length=30)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="participant")
    public Set<Score> getScores() {
        return this.scores;
    }
    
    public void setScores(Set<Score> scores) {
        this.scores = scores;
    }




}


