package com.cbt.entity;
// Generated 12-Jan-2020 16:42:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Question generated by hbm2java
 */
@Entity
@Table(name="question"
    ,catalog="computerbasedtest"
)
public class Question  implements java.io.Serializable {


     private String id;
     private Coursedatabase coursedatabase;
     private Mediacontent mediacontent;
     private User user;
     private String content;
     private Set<Answer> answers = new HashSet<Answer>(0);

    public Question() {
    }

	
    public Question(String id, Coursedatabase coursedatabase, Mediacontent mediacontent, User user, String content) {
        this.id = id;
        this.coursedatabase = coursedatabase;
        this.mediacontent = mediacontent;
        this.user = user;
        this.content = content;
    }
    public Question(String id, Coursedatabase coursedatabase, Mediacontent mediacontent, User user, String content, Set<Answer> answers) {
       this.id = id;
       this.coursedatabase = coursedatabase;
       this.mediacontent = mediacontent;
       this.user = user;
       this.content = content;
       this.answers = answers;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=12)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CourseDatabase_id", nullable=false)
    public Coursedatabase getCoursedatabase() {
        return this.coursedatabase;
    }
    
    public void setCoursedatabase(Coursedatabase coursedatabase) {
        this.coursedatabase = coursedatabase;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MediaContent_id", nullable=false)
    public Mediacontent getMediacontent() {
        return this.mediacontent;
    }
    
    public void setMediacontent(Mediacontent mediacontent) {
        this.mediacontent = mediacontent;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="User_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="content", nullable=false, length=16777215)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="question")
    public Set<Answer> getAnswers() {
        return this.answers;
    }
    
    public void setAnswers(Set<Answer> answers) {
        this.answers = answers;
    }




}


