package com.cbt.entity;
// Generated 12-Jan-2020 16:42:34 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ScoreId generated by hbm2java
 */
@Embeddable
public class ScoreId  implements java.io.Serializable {


     private String testId;
     private String participantId;

    public ScoreId() {
    }

    public ScoreId(String testId, String participantId) {
       this.testId = testId;
       this.participantId = participantId;
    }
   


    @Column(name="Test_id", nullable=false, length=9)
    public String getTestId() {
        return this.testId;
    }
    
    public void setTestId(String testId) {
        this.testId = testId;
    }


    @Column(name="Participant_id", nullable=false, length=11)
    public String getParticipantId() {
        return this.participantId;
    }
    
    public void setParticipantId(String participantId) {
        this.participantId = participantId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ScoreId) ) return false;
		 ScoreId castOther = ( ScoreId ) other; 
         
		 return ( (this.getTestId()==castOther.getTestId()) || ( this.getTestId()!=null && castOther.getTestId()!=null && this.getTestId().equals(castOther.getTestId()) ) )
 && ( (this.getParticipantId()==castOther.getParticipantId()) || ( this.getParticipantId()!=null && castOther.getParticipantId()!=null && this.getParticipantId().equals(castOther.getParticipantId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTestId() == null ? 0 : this.getTestId().hashCode() );
         result = 37 * result + ( getParticipantId() == null ? 0 : this.getParticipantId().hashCode() );
         return result;
   }   


}


