package com.cbt.entity;
// Generated 12-Jan-2020 16:42:34 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Score generated by hbm2java
 */
@Entity
@Table(name="score"
    ,catalog="computerbasedtest"
)
public class Score  implements java.io.Serializable {


     private ScoreId id;
     private Participant participant;
     private Test test;
     private double score;

    public Score() {
    }

    public Score(ScoreId id, Participant participant, Test test, double score) {
       this.id = id;
       this.participant = participant;
       this.test = test;
       this.score = score;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="testId", column=@Column(name="Test_id", nullable=false, length=9) ), 
        @AttributeOverride(name="participantId", column=@Column(name="Participant_id", nullable=false, length=11) ) } )
    public ScoreId getId() {
        return this.id;
    }
    
    public void setId(ScoreId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Participant_id", nullable=false, insertable=false, updatable=false)
    public Participant getParticipant() {
        return this.participant;
    }
    
    public void setParticipant(Participant participant) {
        this.participant = participant;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Test_id", nullable=false, insertable=false, updatable=false)
    public Test getTest() {
        return this.test;
    }
    
    public void setTest(Test test) {
        this.test = test;
    }

    
    @Column(name="score", nullable=false, precision=22, scale=0)
    public double getScore() {
        return this.score;
    }
    
    public void setScore(double score) {
        this.score = score;
    }




}


