package com.cbt.entity;
// Generated 12-Jan-2020 16:42:34 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Subtest generated by hbm2java
 */
@Entity
@Table(name="subtest"
    ,catalog="computerbasedtest"
    , uniqueConstraints = @UniqueConstraint(columnNames="id") 
)
public class Subtest  implements java.io.Serializable {


     private SubtestId id;
     private Coursedatabase coursedatabase;
     private Test test;
     private int amount;

    public Subtest() {
    }

    public Subtest(SubtestId id, Coursedatabase coursedatabase, Test test, int amount) {
       this.id = id;
       this.coursedatabase = coursedatabase;
       this.test = test;
       this.amount = amount;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", unique=true, nullable=false, length=10) ), 
        @AttributeOverride(name="testId", column=@Column(name="Test_id", nullable=false, length=9) ) } )
    public SubtestId getId() {
        return this.id;
    }
    
    public void setId(SubtestId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CourseDatabase_id", nullable=false)
    public Coursedatabase getCoursedatabase() {
        return this.coursedatabase;
    }
    
    public void setCoursedatabase(Coursedatabase coursedatabase) {
        this.coursedatabase = coursedatabase;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Test_id", nullable=false, insertable=false, updatable=false)
    public Test getTest() {
        return this.test;
    }
    
    public void setTest(Test test) {
        this.test = test;
    }

    
    @Column(name="amount", nullable=false)
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }




}


